### ISSUE TITLE
Separate checkmarks for shock, stun, unconsciosness.

### ISSUE THREAD

**Issue by VanessaWGames** [MaxWilson/CageFight#3]
As the title says. It would be nice to split these into different checkmarks.

**Comment by MaxWilson** [comment]
So here's where I'm coming from on the current design: this is essentially Supernatural Durability, but without immunity to crippling (which doesn't exist in CageFight) and immunity to death (which would render CageFight pointless since there's now way to specify the Achilles Heel). I just didn't want to label it Supernatural Durability because I thought that would be confusing.

I don't know any monsters without Supernatural Durability that have immunity to stun and unconsciousness. There _are_ monsters and delvers with High Pain Threshold which gives immunity to shock, but it has other effects as well, like giving you +3 vs. knockdown.

If there were a way to set High Pain Threshold and a way to set Berserk, would you still want separate immunity boxes for shock/stun/unconsciousness?

**Comment by MaxWilson** [comment]
I added High Pain Threshold to the UI. I think that should satisfy all scenarios. Please close this issue if you agree.
